name: anemotaxis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=2.0
  - pandas>=2.0
  - matplotlib>=3.10
  - scipy>=1.10
  - seaborn>=0.11
  - scikit-learn  # For KMeans clustering and PCA
  - h5py  # For reading .mat files
  - ipympl
  - ipywidgets>=8.0  # For interactive plots
  - ipython  # For notebook support
  - jupyter  # For running notebooks
  - pip
  - pip:
    - arrow  # Only essential pip packages kept

prefix: /home/schatterjee/miniconda3/envs/anemotaxis